service: eye2geneclassification

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: eu-central-1
  runtime: python3.7
  profile: phenopolis

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET}
           - "/*"
  environment:
    BUCKET: eye2geneclassifier

functions:
  classifier:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: ping
          method: get
      - http:
          path: ping
          method: post
